[package]
name = "mongodb-crud"
version = "0.1.0"
authors = ["adoxic <griffinmaeve@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "1.0.0"
tokio = "*"